# ==============================================================================
# Calamares - fstab.conf
# Define opções de montagem Btrfs, subvolumes e flags síncronas do crypttab
# ==============================================================================
---
mountOptions:
  default: defaults,noatime
  btrfs: defaults,noatime,compress=zstd:1,ssd,discard=async

ssdExtraMountOptions:
  btrfs: discard=async,compress=zstd:1

crypttabOptions: luks,discard,no-read-workqueue,no-write-workqueue

btrfsSubvolumes:
  - mountPoint: /
    subvolume: /@
  - mountPoint: /home
    subvolume: /@home
  - mountPoint: /var/log
    subvolume: /@log
  - mountPoint: /.snapshots
    subvolume: /@snapshots
