# ==============================================================================
# Calamares - partition.conf
# Define Btrfs padrão e criptografia LUKS2 otimizada (PBKDF2 em 500ms)
# ==============================================================================
---
userSwapChoices:
  - none
initialSwapChoice: none
defaultFileSystemType: "btrfs"
luksGeneration: luks2
luksKeyslotPBKDF:
  type: pbkdf2
  time: 500
