---
dontChroot: false
timeout: 60
script:
  # Garante suporte a cryptodisk no /etc/default/grub do sistema alvo
  - 'echo "GRUB_ENABLE_CRYPTODISK=y" >> /etc/default/grub'
  # Força módulos essenciais no GRUB EFI para LUKS2 + Btrfs
  - 'echo "GRUB_PRELOAD_MODULES=\"luks2 crypto gcry_rijndael gcry_sha256 btrfs\"" >> /etc/default/grub'
