# ==============================================================================
# Calamares - users.conf
# Define grupos modernos, defaults de usuário e desativa root password separada
# ==============================================================================
---
userGroup: users
defaultGroups:
  - sudo
  - users
  - audio
  - video
  - dialout
  - plugdev
  - netdev
  - kvm
  - bluetooth
autologinGroup: autologin
sudoersGroup: sudo
setRootPassword: false
doReusePassword: true

defaultUsername: eu
defaultHostname: fantasma

passwordRequirements:
  nonempty: true
  minLength: -1
  maxLength: -1
  libpwquality:
    - minlen=0
    - minclass=0
