---
# sistema/tasks/00-base.yaml

- name: Configura o TZ para o Brasil
  community.general.timezone:
    name: America/Sao_Paulo
  become: true

- name: Verifica status do NTP
  ansible.builtin.command: timedatectl show --property=NTP --value
  register: ntp_status
  changed_when: false
  become: true

- name: Habilita sincronização de hora via NTP
  ansible.builtin.command: timedatectl set-ntp true
  become: true
  when: ntp_status.stdout != 'yes'

- name: Atualiza cache do apt
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: atualiza_sistema | bool

- name: Realiza atualização completa do sistema
  ansible.builtin.apt:
    upgrade: full
    autoremove: true
    autoclean: true
  become: true
  when: atualiza_sistema | bool

- name: Instala aplicações de sistema
  ansible.builtin.apt:
    name: "{{ pacotes_sistema }}"
    state: present
  become: true

- name: Instala utilitários de diagnóstico de hardware e sistema
  ansible.builtin.apt:
    name: "{{ utilitarios_hardware }}"
    state: present
  become: true

- name: Instala ferramentas para suporte a leitor biométrico (digitais)
  ansible.builtin.apt:
    name: "{{ pacotes_biometria }}"
    state: present
  become: true

- name: Habilita serviços de sistema
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ servicos_sistema }}"
  become: true

- name: Permite conexões SSH no firewall
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Instala aplicações relacionados a terminal
  ansible.builtin.apt:
    name: "{{ apps_terminal }}"
    state: present
  become: true

- name: Instala aplicações de uso gráfico
  ansible.builtin.apt:
    name: "{{ apps_gui }}"
    state: present
  become: true

- name: Instala repositório Flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Instala aplicações do Flatpak
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  loop: "{{ apps_flatpak }}"
  become: true
