---
# sistema/tasks/03-asdf.yaml

- name: Remove instalação anterior do ASDF se solicitado
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin/asdf"
    state: absent
  become: false
  when: asdf_instalacao_limpa | default(false) | bool

- name: Remove .tool-versions anterior do ASDF se solicitado
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.tool-versions"
    state: absent
  become: false
  when: asdf_instalacao_limpa | default(false) | bool

- name: Remove diretório de dados do ASDF se solicitado
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.asdf"
    state: absent
  become: false
  when: asdf_instalacao_limpa | default(false) | bool

- name: Instala dependências do ASDF
  ansible.builtin.apt:
    name:
      - curl
      - git
      - unzip
      - build-essential
      - autoconf
      - libssl-dev
      - libncurses5-dev
      - libreadline-dev
      - libbz2-dev
      - libsqlite3-dev
      - zlib1g-dev
    state: present
  become: true

- name: Cria diretório bin no home se não existir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: '0755'
  become: false

- name: Define ASDF_DATA_DIR
  ansible.builtin.set_fact:
    asdf_data_dir: "{{ ansible_env.HOME }}/.asdf"
  become: false

- name: Verifica se ASDF já está instalado
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/bin/asdf"
  register: asdf_binary
  become: false

- name: Define a URL de download do ASDF
  ansible.builtin.set_fact:
    asdf_download_url: "https://github.com/asdf-vm/asdf/releases/download/{{ versao_asdf }}/asdf-{{ versao_asdf }}-linux-amd64.tar.gz"
  become: false
  when: not asdf_binary.stat.exists

- name: Download do ASDF
  ansible.builtin.get_url:
    url: "{{ asdf_download_url }}"
    dest: "/tmp/asdf.tar.gz"
    mode: '0644'
  become: false
  when: not asdf_binary.stat.exists

- name: Extrai o arquivo
  ansible.builtin.unarchive:
    src: "/tmp/asdf.tar.gz"
    dest: "/tmp"
    remote_src: true
  become: false
  when: not asdf_binary.stat.exists

- name: Instala o binário ASDF
  ansible.builtin.copy:
    src: "/tmp/asdf"
    dest: "{{ ansible_env.HOME }}/bin/asdf"
    mode: '0755'
    remote_src: true
  become: false
  when: not asdf_binary.stat.exists

- name: Adiciona configuração do ASDF ao .bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ASDF CONFIGURATION"
    block: |
      # ASDF Version Manager (v0.16.x)
      export ASDF_DATA_DIR="{{ asdf_data_dir }}"
      export PATH="$ASDF_DATA_DIR/shims:$PATH"
    state: present
  become: false
