---
# sistema/tasks/05-kvm-qemu.yaml

- name: Instala pacotes de virtualização
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ pacotes_virt }}"
  become: true

- name: Adiciona usuário aos grupos de virtualização
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: "{{ item }}"
    append: true
  loop: "{{ grupos_virt }}"
  become: true

- name: Configura serviço libvirtd
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ servicos_virt }}"
  become: true
