---
# sistema/tasks/09-tailscale.yaml

- name: Instalação e configuração do Tailscale VPN
  become: true
  block:
    - name: Instala o pacote do Tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present

    - name: Habilita e inicia o serviço do Tailscale
      ansible.builtin.systemd_service:
        name: tailscaled.service
        state: started
        enabled: true
