---
# sistema/tasks/99-gnome-extensions.yaml

- name: Configuração das extensões GNOME
  block:
    - name: Instala pacotes do sistema para extensões e integração Python
      become: true
      ansible.builtin.apt:
        name:
          - python3-gi
          - gnome-shell-extensions
        state: present

    - name: Garante instalação do gnome-extensions-cli (gext) via pipx
      community.general.pipx:
        name: gnome-extensions-cli
        system_site_packages: true
        state: present
      become: false

    - name: Obtém lista de extensões já instaladas no disco
      ansible.builtin.command:
        cmd: "{{ ansible_env.HOME }}/.local/bin/gext --filesystem list"
      register: gext_installed_output
      changed_when: false
      become: false

    - name: Instala extensões GNOME via gext (backend filesystem)
      ansible.builtin.command:
        cmd: "{{ ansible_env.HOME }}/.local/bin/gext --filesystem install {{ item.id }}"
      loop: "{{ extensoes_gnome }}"
      loop_control:
        label: "{{ item.nome }} ({{ item.id }})"
      when: (item.nome not in gext_installed_output.stdout) and ((item.id | string) not in gext_installed_output.stdout)
      become: false
      register: gext_install_res
      changed_when: "'Extract extension' in gext_install_res.stdout"

    - name: Garante diretório de papéis de parede do usuário
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/backgrounds"
        state: directory
        mode: '0755'
      become: false

    - name: Copia papel de parede Bliss para a pasta de backgrounds
      ansible.builtin.copy:
        src: bliss.jpg
        dest: "{{ ansible_env.HOME }}/.local/share/backgrounds/bliss.jpg"
        mode: '0644'
      become: false

    - name: Garante diretório de perfis do Burn My Windows
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/burn-my-windows/profiles"
        state: directory
        mode: '0755'
      become: false

    - name: Copia perfil personalizado do Burn My Windows
      ansible.builtin.copy:
        src: burn-my-windows/transicoes.conf
        dest: "{{ ansible_env.HOME }}/.config/burn-my-windows/profiles/transicoes.conf"
        mode: '0644'
      become: false

    - name: Renderiza arquivo de preferências GNOME (janelas, atalhos, extensões e wallpaper)
      ansible.builtin.template:
        src: gnome-desktop.dconf.j2
        dest: "{{ ansible_env.HOME }}/.config/gnome-desktop.dconf"
        mode: '0600'
      register: dconf_template_res
      become: false

    - name: Aplica configurações personalizadas do GNOME via dconf quando houver alterações
      ansible.builtin.shell: |
        dconf load / < "{{ ansible_env.HOME }}/.config/gnome-desktop.dconf"
      environment:
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_uid }}/bus"
      when: dconf_template_res.changed
      become: false
      changed_when: true
