---
# sistema/tasks/main.yaml

- name: Importar configurações base
  ansible.builtin.import_tasks: 00-base.yaml

- name: Importar configurações de repositório
  ansible.builtin.import_tasks: 01-extrepo.yaml

- name: Importar configurações de usuário
  ansible.builtin.import_tasks: 02-usuario.yaml

- name: Importar configurações do ASDF
  ansible.builtin.import_tasks: 03-asdf.yaml

- name: Importar configurações dos shims para ASDF
  ansible.builtin.import_tasks: 04-asdf-shims.yaml

- name: Importar configurações de virtualização
  ansible.builtin.import_tasks: 06-vagrant-kvm-qemu.yaml

- name: Instalar LogSeq
  ansible.builtin.import_tasks: 07-logseq.yaml

- name: Importar configurações das extensões GNOME
  ansible.builtin.import_tasks: 99-gnome-extensions.yaml
