---
# sistema/handlers/main.yaml

# Handlers para ASDF reshim
- name: Reshim
  ansible.builtin.shell: |
    export ASDF_DATA_DIR="{{ asdf_data_dir }}"
    export PATH="$ASDF_DATA_DIR/shims:$HOME/.local/bin:$PATH"
    asdf reshim
  args:
    executable: /bin/bash
  become: false
  changed_when: true

# Handler para sincronização de metadados e chaves do Extrepo
- name: Atualiza metadados do extrepo
  ansible.builtin.command: extrepo update
  become: true
  changed_when: true

# Handlers para serviços de rede e resolução DNS
- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    state: restarted
  become: true

- name: Restart NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager.service
    state: restarted
  become: true

# Handlers para regras do udev
- name: Recarrega regras do udev
  ansible.builtin.command: udevadm control --reload-rules
  become: true
  changed_when: true
  notify: Dispara regras do udev

- name: Dispara regras do udev
  ansible.builtin.command: udevadm trigger
  become: true
  changed_when: true

